---
- hosts: enterprise
  gather_facts: False
  pre_tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  
  roles:
    - php-config-test #this is a test to modify a php.ini file
